//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 414
#pragma warning disable 649
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace OrleansExample.Interfaces.Advanced
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using OrleansExample.Interfaces.Advanced;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class CustomerGrainFactory
    {
        

                        public static OrleansExample.Interfaces.Advanced.ICustomerGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansExample.Interfaces.Advanced.ICustomerGrain), -725616150, primaryKey));
                        }

                        public static OrleansExample.Interfaces.Advanced.ICustomerGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansExample.Interfaces.Advanced.ICustomerGrain), -725616150, primaryKey, grainClassNamePrefix));
                        }

            public static OrleansExample.Interfaces.Advanced.ICustomerGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return CustomerGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("OrleansExample.Interfaces.Advanced.OrleansExample.Interfaces.Advanced.ICustomerGr" +
            "ain")]
        internal class CustomerGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, OrleansExample.Interfaces.Advanced.ICustomerGrain
        {
            

            public static OrleansExample.Interfaces.Advanced.ICustomerGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (OrleansExample.Interfaces.Advanced.ICustomerGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(OrleansExample.Interfaces.Advanced.ICustomerGrain), (global::Orleans.Runtime.GrainReference gr) => { return new CustomerGrainReference(gr);}, grainRef, -725616150);
            }
            
            protected internal CustomerGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal CustomerGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -725616150;
                }
            }
            
            public override string InterfaceName
            {
                get
                {
                    return "OrleansExample.Interfaces.Advanced.OrleansExample.Interfaces.Advanced.ICustomerGr" +
                        "ain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                CustomerGrainReference input = ((CustomerGrainReference)(original));
                return ((CustomerGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                CustomerGrainReference input = ((CustomerGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return CustomerGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1097320095));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return CustomerGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task OrleansExample.Interfaces.Advanced.ICustomerGrain.SetName(string @name)
            {

                return base.InvokeMethodAsync<object>(316304768, new object[] {@name} );
            }
            
            System.Threading.Tasks.Task<OrleansExample.Interfaces.Advanced.Customer> OrleansExample.Interfaces.Advanced.ICustomerGrain.GetModel()
            {

                return base.InvokeMethodAsync<OrleansExample.Interfaces.Advanced.Customer>(1535020019, null );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("OrleansExample.Interfaces.Advanced.OrleansExample.Interfaces.Advanced.ICustomerGr" +
        "ain", -725616150)]
    internal class CustomerGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -725616150;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -725616150:  // ICustomerGrain
                        switch (methodId)
                        {
                            case 316304768: 
                                return ((ICustomerGrain)grain).SetName((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1535020019: 
                                return ((ICustomerGrain)grain).GetModel().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1097320095:  // IGrainWithGuidKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -725616150:  // ICustomerGrain
                    switch (methodId)
                    {
                        case 316304768:
                            return "SetName";
                    case 1535020019:
                            return "GetModel";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1097320095:  // IGrainWithGuidKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class CustomerIndexerFactory
    {
        

                        public static OrleansExample.Interfaces.Advanced.ICustomerIndexer GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansExample.Interfaces.Advanced.ICustomerIndexer), -1446026602, primaryKey));
                        }

                        public static OrleansExample.Interfaces.Advanced.ICustomerIndexer GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansExample.Interfaces.Advanced.ICustomerIndexer), -1446026602, primaryKey, grainClassNamePrefix));
                        }

            public static OrleansExample.Interfaces.Advanced.ICustomerIndexer Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return CustomerIndexerReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("OrleansExample.Interfaces.Advanced.OrleansExample.Interfaces.Advanced.ICustomerIn" +
            "dexer")]
        internal class CustomerIndexerReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, OrleansExample.Interfaces.Advanced.ICustomerIndexer
        {
            

            public static OrleansExample.Interfaces.Advanced.ICustomerIndexer Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (OrleansExample.Interfaces.Advanced.ICustomerIndexer) global::Orleans.Runtime.GrainReference.CastInternal(typeof(OrleansExample.Interfaces.Advanced.ICustomerIndexer), (global::Orleans.Runtime.GrainReference gr) => { return new CustomerIndexerReference(gr);}, grainRef, -1446026602);
            }
            
            protected internal CustomerIndexerReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal CustomerIndexerReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -1446026602;
                }
            }
            
            public override string InterfaceName
            {
                get
                {
                    return "OrleansExample.Interfaces.Advanced.OrleansExample.Interfaces.Advanced.ICustomerIn" +
                        "dexer";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                CustomerIndexerReference input = ((CustomerIndexerReference)(original));
                return ((CustomerIndexerReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                CustomerIndexerReference input = ((CustomerIndexerReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return CustomerIndexerReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == 1928988877));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return CustomerIndexerMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task OrleansExample.Interfaces.Advanced.ICustomerIndexer.IndexCustomer(OrleansExample.Interfaces.Advanced.Customer @customer)
            {

                return base.InvokeMethodAsync<object>(2124991640, new object[] {@customer} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("OrleansExample.Interfaces.Advanced.OrleansExample.Interfaces.Advanced.ICustomerIn" +
        "dexer", -1446026602)]
    internal class CustomerIndexerMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -1446026602;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -1446026602:  // ICustomerIndexer
                        switch (methodId)
                        {
                            case 2124991640: 
                                return ((ICustomerIndexer)grain).IndexCustomer((Customer)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case 1928988877:  // IGrainWithIntegerKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -1446026602:  // ICustomerIndexer
                    switch (methodId)
                    {
                        case 2124991640:
                            return "IndexCustomer";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case 1928988877:  // IGrainWithIntegerKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class OrleansExample_Interfaces_Advanced_CustomerSerialization
    {
        
        static OrleansExample_Interfaces_Advanced_CustomerSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            OrleansExample.Interfaces.Advanced.Customer input = ((OrleansExample.Interfaces.Advanced.Customer)(original));
            OrleansExample.Interfaces.Advanced.Customer result = new OrleansExample.Interfaces.Advanced.Customer();
            Orleans.Serialization.SerializationContext.Current.RecordObject(original, result);
            result.Id = ((System.Guid)(Orleans.Serialization.SerializationManager.DeepCopyInner(input.Id)));
            result.Name = input.Name;
            return result;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            OrleansExample.Interfaces.Advanced.Customer input = ((OrleansExample.Interfaces.Advanced.Customer)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(System.Guid));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(string));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            OrleansExample.Interfaces.Advanced.Customer result = new OrleansExample.Interfaces.Advanced.Customer();
            result.Id = ((System.Guid)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(System.Guid), stream)));
            result.Name = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(OrleansExample.Interfaces.Advanced.Customer), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 649
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
